apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coupon-app
  template:
    metadata:
      labels:
        app: coupon-app
    spec:
      containers:
      - name: coupon-app
        image: aymansce/coupon-services:v1.2
        ports:
        - containerPort: 8080
